# Generated by Django 5.2.1 on 2026-01-22 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre de la empresa')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='finanzas_comercial/company_logos/', verbose_name='Logo')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=120, verbose_name='Apellido')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo')),
                ('phone', models.CharField(blank=True, max_length=40, null=True, verbose_name='Número de teléfono')),
                ('job_title', models.CharField(blank=True, max_length=160, null=True, verbose_name='Cargo')),
                ('linkedin_url', models.URLField(blank=True, null=True, verbose_name='LinkedIn')),
                ('last_activity_at', models.DateTimeField(blank=True, null=True, verbose_name='Última actividad')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='finanzas_comercial.company', verbose_name='Empresa')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts_owned', to=settings.AUTH_USER_MODEL, verbose_name='Propietario del contacto')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['email'], name='finanzas_co_email_ebde97_idx'), models.Index(fields=['last_name', 'first_name'], name='finanzas_co_last_na_053619_idx'), models.Index(fields=['created_at'], name='finanzas_co_created_79a1e9_idx')],
            },
        ),
    ]
