# Generated by Django 5.2.1 on 2026-01-22 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas_comercial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='finanzas_comercial/contact_logos/', verbose_name='Logo del contacto'),
        ),
    ]
