# Generated by Django 5.2.1 on 2026-01-22 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas_comercial', '0002_contact_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='company',
            name='country_region',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='País/Región'),
        ),
        migrations.AddField(
            model_name='company',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies_created', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AddField(
            model_name='company',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última actividad'),
        ),
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Número de contacto'),
        ),
        migrations.AddField(
            model_name='company',
            name='rut',
            field=models.CharField(blank=True, db_index=True, default='', max_length=30, verbose_name='RUT'),
        ),
        migrations.AddField(
            model_name='company',
            name='sector',
            field=models.CharField(blank=True, default='', max_length=160, verbose_name='Rubro / Sector'),
        ),
        migrations.AddField(
            model_name='company',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado'),
        ),
        migrations.AlterField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['name'], name='finanzas_co_name_7c29d9_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['rut'], name='finanzas_co_rut_206611_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['created_at'], name='finanzas_co_created_fe8db6_idx'),
        ),
    ]
