# Generated by Django 5.2.1 on 2026-01-22 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas_comercial', '0003_company_city_company_country_region_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DealStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Etapa')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deal_stages_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Etapa de negocio',
                'verbose_name_plural': 'Etapas de negocio',
                'ordering': ['sort_order', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del negocio')),
                ('close_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cierre')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Valor del negocio')),
                ('last_activity_at', models.DateTimeField(blank=True, null=True, verbose_name='Última actividad')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='finanzas_comercial.company', verbose_name='Empresa')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals_owned', to=settings.AUTH_USER_MODEL, verbose_name='Propietario del negocio')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='finanzas_comercial.dealstage', verbose_name='Etapa del negocio')),
            ],
            options={
                'verbose_name': 'Negocio',
                'verbose_name_plural': 'Negocios',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='dealstage',
            index=models.Index(fields=['name'], name='finanzas_co_name_e9edda_idx'),
        ),
        migrations.AddIndex(
            model_name='dealstage',
            index=models.Index(fields=['is_active'], name='finanzas_co_is_acti_3acb79_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['name'], name='finanzas_co_name_2a0dff_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['created_at'], name='finanzas_co_created_8d6632_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['close_at'], name='finanzas_co_close_a_d8ff75_idx'),
        ),
    ]
