# Generated by Django 5.2.1 on 2026-01-23 17:29

import django.db.models.deletion
import django.utils.timezone
import finanzas_comercial.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas_comercial', '0004_dealstage_deal_dealstage_finanzas_co_name_e9edda_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('last_contact_at', models.DateTimeField(blank=True, null=True, verbose_name='Último contacto')),
                ('due_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de vencimiento')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('notify_by_email', models.BooleanField(default=False, verbose_name='Notificar por correo')),
                ('status', models.CharField(choices=[('EN_PROCESO', 'En proceso'), ('COMPLETADA', 'Completada'), ('PEND_EXTERNO', 'Pendiente por persona externa')], default='EN_PROCESO', max_length=20, verbose_name='Estatus')),
                ('status_comment', models.TextField(blank=True, verbose_name='Comentario del estatus')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comercial_tasks_assigned', to=settings.AUTH_USER_MODEL, verbose_name='Asignada a')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='finanzas_comercial.company', verbose_name='Empresa asociada')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='finanzas_comercial.contact', verbose_name='Contacto asociado')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comercial_tasks_created', to=settings.AUTH_USER_MODEL, verbose_name='Creada por')),
            ],
            options={
                'verbose_name': 'Tarea Comercial',
                'verbose_name_plural': 'Tareas Comerciales',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TaskAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=finanzas_comercial.models.task_attachment_upload_to, verbose_name='Archivo')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='Nombre original')),
                ('content_type', models.CharField(blank=True, max_length=100, verbose_name='Tipo MIME')),
                ('size_bytes', models.BigIntegerField(default=0, verbose_name='Tamaño (bytes)')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha subida')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='finanzas_comercial.task', verbose_name='Tarea')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comercial_task_attachments', to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
            ],
            options={
                'verbose_name': 'Adjunto de Tarea',
                'verbose_name_plural': 'Adjuntos de Tarea',
                'ordering': ['-uploaded_at', '-id'],
            },
        ),
    ]
