# Generated by Django 5.2.1 on 2026-01-23 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas_comercial', '0005_task_taskattachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='last_contact_at',
        ),
    ]
