# Generated by Django 5.2.1 on 2026-01-23 18:00

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas_comercial', '0006_remove_task_last_contact_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de completada'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Fecha creación'),
        ),
        migrations.AlterField(
            model_name='task',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Activa'),
        ),
        migrations.AlterField(
            model_name='task',
            name='notify_by_email',
            field=models.BooleanField(default=False, verbose_name='Notificar por correo al crear'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('EN_PROCESO', 'En proceso'), ('COMPLETADA', 'Completada'), ('PEND_EXTERNO', 'Pendiente por persona externa')], db_index=True, default='EN_PROCESO', max_length=20, verbose_name='Estatus'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status'], name='finanzas_co_status_b68dd8_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['is_active'], name='finanzas_co_is_acti_0655c0_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['due_at'], name='finanzas_co_due_at_35e292_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['created_at'], name='finanzas_co_created_7fead6_idx'),
        ),
    ]
