# Generated by Django 5.2.1 on 2026-01-23 20:59

import django.db.models.deletion
import django.utils.timezone
import finanzas_comercial.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas_comercial', '0007_task_completed_at_alter_task_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título del presupuesto')),
                ('status', models.CharField(choices=[('ENVIADA', 'Enviada'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('EN_MODIFICACION', 'En modificación')], db_index=True, default='EN_MODIFICACION', max_length=20, verbose_name='Estado de la cotización')),
                ('status_comment', models.TextField(blank=True, default='', verbose_name='Comentario del estado')),
                ('amount_clp', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Importe del presupuesto (CLP)')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Fecha de vencimiento')),
                ('comments', models.TextField(blank=True, default='', verbose_name='Comentarios')),
                ('purchase_conditions', models.TextField(blank=True, default='', verbose_name='Condiciones de compra')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to=finanzas_comercial.models.quote_pdf_upload_to, verbose_name='Cotización PDF')),
                ('pdf_reference', models.CharField(blank=True, db_index=True, default='', max_length=80, verbose_name='Referencia')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activa')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('contacts', models.ManyToManyField(blank=True, related_name='quotes', to='finanzas_comercial.contact', verbose_name='Contactos asociados')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commercial_quotes_created', to=settings.AUTH_USER_MODEL, verbose_name='Creada por')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='finanzas_comercial.deal', verbose_name='Negocio asociado')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commercial_quotes_owned', to=settings.AUTH_USER_MODEL, verbose_name='Propietario de la cotización')),
                ('prepared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commercial_quotes_prepared', to=settings.AUTH_USER_MODEL, verbose_name='Preparado por')),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='QuoteLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título / ítem')),
                ('qty', models.DecimalField(decimal_places=2, default=1, max_digits=18, verbose_name='Cantidad')),
                ('unit_price_clp', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Monto (CLP)')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finanzas_comercial.quote', verbose_name='Cotización')),
            ],
            options={
                'verbose_name': 'Línea de cotización',
                'verbose_name_plural': 'Líneas de cotización',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['status'], name='finanzas_co_status_a167ee_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['created_at'], name='finanzas_co_created_0e3a4b_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['expires_at'], name='finanzas_co_expires_c5615f_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['is_active'], name='finanzas_co_is_acti_a12596_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['pdf_reference'], name='finanzas_co_pdf_ref_9781da_idx'),
        ),
        migrations.AddIndex(
            model_name='quoteline',
            index=models.Index(fields=['quote'], name='finanzas_co_quote_i_eea696_idx'),
        ),
    ]
