# Generated by Django 5.2.1 on 2026-01-27 18:07

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas_comercial', '0008_quote_quoteline_quote_finanzas_co_status_a167ee_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteline',
            name='discount_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Descuento (%)'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('CREADA', 'Creada'), ('ENVIADA', 'Enviada'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('EN_MODIFICACION', 'En modificación')], db_index=True, default='CREADA', max_length=20, verbose_name='Estado de la cotización'),
        ),
    ]
