# Generated by Django 5.2.1 on 2026-01-27 20:53

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas_comercial', '0009_quoteline_discount_pct_alter_quote_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='currency',
            field=models.CharField(choices=[('CLP', 'CLP'), ('USD', 'USD')], db_index=True, default='CLP', max_length=3, verbose_name='Moneda'),
        ),
        migrations.AddField(
            model_name='quote',
            name='extra_discount_name',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Nombre descuento'),
        ),
        migrations.AddField(
            model_name='quote',
            name='extra_discount_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Descuento extra (%)'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='amount_clp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Importe del presupuesto'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['currency'], name='finanzas_co_currenc_856527_idx'),
        ),
    ]
