# Generated by Django 5.2.1 on 2026-01-28 12:46

import django.db.models.deletion
import django.utils.timezone
import finanzas_comercial.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas_comercial', '0010_quote_currency_quote_extra_discount_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DealAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('INICIAL', 'Inicial (RFP)'), ('ANALISIS', 'Análisis')], db_index=True, default='INICIAL', max_length=20, verbose_name='Tipo')),
                ('file', models.FileField(upload_to=finanzas_comercial.models.deal_attachment_upload_to, verbose_name='Archivo')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='Nombre original')),
                ('content_type', models.CharField(blank=True, max_length=100, verbose_name='Tipo MIME')),
                ('size_bytes', models.BigIntegerField(default=0, verbose_name='Tamaño (bytes)')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha subida')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='finanzas_comercial.deal', verbose_name='Negocio')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comercial_deal_attachments', to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
            ],
            options={
                'verbose_name': 'Adjunto de Negocio',
                'verbose_name_plural': 'Adjuntos de Negocio',
                'ordering': ['-uploaded_at', '-id'],
                'indexes': [models.Index(fields=['deal', 'category'], name='finanzas_co_deal_id_2b88c5_idx'), models.Index(fields=['uploaded_at'], name='finanzas_co_uploade_53d520_idx')],
            },
        ),
    ]
