# Generated by Django 5.2.1 on 2026-01-19 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_trusteddevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='twofa_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
