# Generated by Django 5.2.1 on 2026-01-19 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_user_twofa_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rut',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20),
        ),
    ]
