# Generated by Django 5.2.1 on 2026-01-19 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_user_rut'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_notificaciones_activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_activo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_chat_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
